"""Initial migration

Revision ID: 3667e1734d31
Revises: 8aa162b2027d
Create Date: 2024-04-11 11:09:35.288106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3667e1734d31'
down_revision = '8aa162b2027d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('companies')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('contact')
        batch_op.drop_index('email')

    op.drop_table('users')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('isbn')

    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('price_unit', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('publication_date', sa.DATE(), nullable=False),
    sa.Column('isbn', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('genre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('pages', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='books_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='books_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('isbn', ['isbn'], unique=True)

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('contact', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('user_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('biography', mysql.TEXT(), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.create_index('contact', ['contact'], unique=True)

    op.create_table('companies',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('origin', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='companies_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    # ### end Alembic commands ###
