"""Migrating books, companies,users

Revision ID: 4d09c933b7d2
Revises: 409152b1839e
Create Date: 2024-04-03 14:48:54.233580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d09c933b7d2'
down_revision = '409152b1839e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pages', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.alter_column('image',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('price_unit',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])
        batch_op.drop_column('number_of_pages')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=True)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_pages', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('price_unit',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               nullable=False)
        batch_op.drop_column('company_id')
        batch_op.drop_column('pages')

    # ### end Alembic commands ###
